spring:
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 30MB
  datasource:
    url: jdbc:mysql://hello-there.cttuoh0xl2hh.ap-northeast-2.rds.amazonaws.com:3306/MyDB?userSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&autoReconnect=True
    username : root
    password : wdrsus0520
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
cloud:
  aws:
    s3:
      bucket: hello-there-spring
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      access-key: AKIA2NCQDTVFSGP6Y7JI
      secret-key: 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


